project:
  type: website
  output-dir: docs

website:
  title: "Collab Website - Connor + Azwad"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resources.qmd

format:
  html:
    theme: Flatly
      - cosmo
      - brand
    css: styles.css
    toc: true



